# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b0d6282d72d8b2ba213a3f674e32c4fd193b88241b013e6c1bd0be0d7b8de973debba6b643f600168851e001c8b9b2ab07fd6c9aa0fd690faeb506ae6b092a5

test:
  secret_key_base: d277f31bc3d074612d881e46451e6a4a306174caadbfb1f30881fc6444f572c38bf9cebbcdfe8d9bde98da879abfdf83366a0e16bee09db623c1738ac639af93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
